# Generated by Django 3.0.4 on 2020-04-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200405_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='Settings',
        ),
    ]
